# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 20 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: sgatrac
google_analytics: dbyll
title: serkan haytac

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Serkan Haytac

description: Stylish Jekyll Theme
author:
  name: serkan haytac
  email: shaytac at gmail.com
  github: serkanh
  twitter: shaytac
#  pinterest: asd123
  linkedin: serkanhaytac
  bio:  <a href="https://www.certmetrics.com/amazon/public/badge.aspx?i=1&t=c&d=2016-07-01&ci=AWS00186868">AWS Certified Solutions Architect - Associate</a><br /><a href="https://www.certmetrics.com/amazon/public/badge.aspx?i=2&t=c&d=2016-07-23&ci=AWS00186868">AWS Certified Developer - Associate</a><br /><a href="https://www.certmetrics.com/amazon/public/badge.aspx?i=3&t=c&d=2018-01-12&ci=AWS00186868">AWS Certified SysOps Administrator - Associate</a><br /> <a href="https://gist.github.com/serkanh">Gists</>
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
